name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # Step 3: Cache Maven dependencies (optional but speeds up the workflow)
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    # Step 5: Run the tests
    - name: Run tests with Maven
      run: mvn test

    # Step 6: Deploy (For example, deploy to a remote server or cloud)
    # Add your deployment steps here.
    # For demonstration, we can use a placeholder for deployment
    - name: Deploy
      run: echo "Deploying application..."
